package com.ahmad.jobBoard;

public enum Industry {
    TECHNOLOGY,
    FINANCE,
    HEALTHCARE,
    EDUCATION,
    RETAIL,
    MANUFACTURING,
    CONSTRUCTION,
    HOSPITALITY,
    TRANSPORTATION,
    ENERGY,
    TELECOMMUNICATIONS,
    MEDIA,
    GOVERNMENT,
    NON_PROFIT,
    OTHER
}
